linters:
  enable:
    - errorlint
    - forbidigo
    - gochecknoinits
    - gocritic
    - gofumpt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - wastedassign
linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gofumpt:
    extra-rules: true
